### ISSUE TITLE
Version 0.0.3

### ISSUE THREAD

**Issue by theshka** [theshka/MJTS_GTFS#1]
# TO-DO

Wiki
- [x] Update wiki with agency information

Script
- [ ] Add fare data?
- [ ] Add all trips for all routes See #2 
- [ ] Extrapolate stop-times for missing stops See #2 
- [x] Multiple schedules: Regular/Late-Night
- [x] Add Saturday Service

Stops
- [ ] Any missing? Any extra?
- [ ] Latitude & longitude of stops are inaccurate.

Stop Times
- [ ] Times are approximate, MJTS is not equipped with GPS

Deploy
- [ ] Where to host this feed?
- [ ] Automatic feed generation on GitHub release?
- [ ] [Submit](http://maps.google.com/help/maps/mapcontent/transit/participate.html) to Google Transit
